"""Regenerate reports/INDEX.md from YAML frontmatter in reports/*.md.

Every report needs a frontmatter block:

    ---
    title: Short title
    description: One-sentence summary
    tags: [tag-one, tag-two, latincy-dev]
    date: YYYY-MM-DD
    script: experiments/matching_topic.py   # optional
    ---

`latincy-dev` (or any tag) is just a keyword — there's no dedicated "audience"
field. Tag a report with it when its findings are actionable for the LatinCy
maintainer; a report can carry as many or as few tags as make sense.

Run after adding or editing a report: `python3 build_report_index.py`.
"""

import sys
from pathlib import Path

import yaml

REPORTS_DIR = Path(__file__).parent / "reports"
INDEX_PATH = REPORTS_DIR / "INDEX.md"


def load_frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path.name}: missing frontmatter block")
    end = text.index("\n---\n", 4)
    fm = yaml.safe_load(text[4:end])
    fm["_path"] = path
    return fm


def main():
    reports = []
    errors = []
    for path in sorted(REPORTS_DIR.glob("*.md")):
        if path.name == "INDEX.md":
            continue
        try:
            reports.append(load_frontmatter(path))
        except Exception as e:
            errors.append(f"{path.name}: {e}")

    if errors:
        print("Skipped files with bad/missing frontmatter:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)

    reports.sort(key=lambda r: r.get("date", ""), reverse=True)

    lines = [
        "# Report index",
        "",
        "Regenerated by `build_report_index.py` — do not hand-edit, run the",
        "script instead after adding/editing a report's frontmatter.",
        "",
        "## All reports",
        "",
        "| Date | Title | Tags | Script |",
        "|---|---|---|---|",
    ]
    for r in reports:
        name = r["_path"].name
        title = r.get("title", name)
        date = r.get("date", "")
        tags = ", ".join(r.get("tags", []))
        script = r.get("script", "")
        script_link = f"[{script}](../{script})" if script else ""
        lines.append(f"| {date} | [{title}]({name}) | {tags} | {script_link} |")

    tag_index = {}
    for r in reports:
        for tag in r.get("tags", []):
            tag_index.setdefault(tag, []).append(r)

    lines += ["", "## By tag", ""]
    for tag in sorted(tag_index):
        lines.append(f"### `{tag}`")
        lines.append("")
        for r in tag_index[tag]:
            desc = r.get("description", "")
            lines.append(f"- [{r.get('title', r['_path'].name)}]({r['_path'].name}) — {desc}")
        lines.append("")

    INDEX_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {INDEX_PATH} ({len(reports)} reports, {len(tag_index)} tags)")


if __name__ == "__main__":
    main()
